name: Report Bug (上报 Bug)
description: Submit a bug report in Chinese (使用中文进行 Bug 报告)
labels: ['bug']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before asking... (在提问之前...)
      options:
      - label: I have searched existing issues (我已经搜索了现有的 issues)
        required: true
      - label: I have spent at least 5 minutes thinking about and preparing my question (我在提问题之前至少花费了 5 分钟来思考和准备)
        required: true
      - label: I have carefully and completely read the wiki (我已经认真且完整的阅读了 wiki)
        required: true
      - label: I have verified the issue is not network-related (including but not limited to Google unavailability, model download failure) (我已经认真检查了问题和网络环境无关（包括但不限于Google不可用，模型下载失败）)
        required: true
  - type: markdown
    attributes:
      value: |
        Thank you for using this project and providing feedback! (感谢您使用本项目并反馈！)
        Please confirm that you have carefully followed the requirements in the checkboxes above! (请再次确认上述复选框所述的内容已经认真执行！)
  - type: textarea
    id: environment
    attributes:
<<<<<<< Updated upstream
      label: 使用的环境
      placeholder: |
          - **OS**: Ubuntu 24.10  
          - **Python**: 3.12.0  
          - **pdf2zh**: 1.9.0
=======
      label: Environment Used (使用的环境)
      description: |
        examples:
          - **OS**: Ubuntu 24.10  
          - **Python**: 3.12.0  
          - **drpdf**: 1.9.7
      value: |
          - OS:
          - Python:
          - drpdf:
>>>>>>> Stashed changes
      render: markdown
    validations:
      required: false
  - type: dropdown
    id: install
    attributes:
      label: Installation Method (安装方式)
      options:
        - pip
        - exe
        - source code (源码)
        - docker
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe Your Issue (描述你的问题)
      description: Briefly describe your issue (简要描述你的问题)
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce (如何复现)
      description: Steps to reproduce this behavior (重现该行为的步骤)
      value: |
        1. Execute '...'
        2. Select '....'
        3. Issue occurs
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior (预期行为)
      description: Briefly describe what you expected to happen (简要描述你期望得到的反馈)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Related Logs (相关 Logs)
      description: Please copy and paste any relevant log output (请复制并粘贴任何相关的日志输出)
      render: Text
    validations:
      required: false
  - type: textarea
    id: PDFfile
    attributes:
      label: Original PDF File (原始PDF文件)
      description: |
        If the issue involves layout errors, please provide the original PDF file for reproduction (如果涉及到排版错误的问题，请一定提供原始的PDF文件，方便复现错误)
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Anything Else? (还有别的吗？)
      description: |
        Related configuration? Links? References? (相关的配置？链接？参考资料？)
        Anything that can help us better understand your issue (任何能让我们对你所遇到的问题有更多了解的东西)
    validations:
      required: false