name: 问题反馈
description: 创建问题报告以帮助我们改进
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此错误报告！
  - type: textarea
    id: environment
    attributes:
      label: 使用环境
      description: 您正在运行我们软件的哪个版本？
      placeholder: |
        - **drpdf**: 2.0.0
        - **Python**: 3.10.0
        - **OS**: Windows 10
      value: |
        - OS:
        - Python:
        - drpdf:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 同时告诉我们，您期望发生什么？
      placeholder: 告诉我们您看到了什么！
      value: "发生了一个错误！"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 相关日志输出
      description: 请复制并粘贴任何相关的日志输出。这将自动格式化为代码，因此无需使用反引号。
      render: shell